# Generated by Django 2.1.5 on 2019-01-15 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190115_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
